### PR TITLE
Fix WASM mime type error

### LINKED ISSUE #1: Try fix from Rollup Discord
From José in the Rollup Discord:

> ... fixed by adding the following custom vite plugin as it was suggested on some repo I visited

```
const wasmContentTypePlugin = {
  name: 'wasm-content-type-plugin',
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      if (req.url.endsWith('.wasm')) {
        res.setHeader('Content-Type', 'application/wasm');
      }
      next();
    });
  },
};
```

### PR DESCRIPTION
**Pull request by curran**
closes #1

Before:

image

### CODE REVIEW

**Comment by curran** [comment]
Current status: Fixed the original content-type error!

Now it's failing on not resolving the WASM file.

The error I see now:

```
main.ts:8     GET http://localhost:5173/node_modules/.vite/deps/bindings_wasm_bg.wasm net::ERR_ABORTED 404 (Not Found)
```

image


The URL looks totally bogus, as I don't believe Vite would not be serving up `node_modules`. How can we serve the `.wasm` file as an asset? Where does this file even come from?

**Comment by sadn1ck** [comment]
You need a vite.config.ts with

```ts
import {defineConfig} from 'vite'

export default defineConfig({
  optimizeDeps: {
    exclude: ["@rollup/browser"]
  }
})
```

**Comment by curran** [comment]
Whoah amazing! That works! Thank you so much.

**Comment by eltaiguer** [comment]
@sadn1ck thank you, you're a lifesaver!

**Pull request merged**
